version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  person-service:
    build: .
    container_name: person-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./src/config-gh.yaml:/usr/local/etc/apiserver/config.yaml
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://person-service:8080/readiness"]
      interval: 1m30s
      timeout: 10s
      retries: 6
      start_period: 10s

volumes:
  db-data:
