with-expecter: True
inpackage: True
dir: ./{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName }}.go"
tags: testing
all: True
packages:
  github.com/migregal/bmstu-iu7-ds-lab1/apiserver/core:
    config:
      # dir: apiserver/core/ports/mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
      recursive: True
